---
title: "Galaxy API R Client"
output:
  html_document:
    df_print: paged
---
## The Galaxy container image

[README](https://github.com/bgruening/docker-galaxy-stable) contains detailed instructions
for controlling the container behavior.

In particular, [this section](https://github.com/bgruening/docker-galaxy-stable#Galaxys-config-settings)
decsribes default values of the admin account name, and the way to override it.
The default is:
```
GALAXY_CONFIG_ADMIN_USERS=admin@galaxy.org
```
and the password is `admin`.

You can override in this way any parameter from the [galaxy config file](https://github.com/galaxyproject/galaxy/blob/release_19.01/config/galaxy.yml.sample). 
This is not a container feature, this is a core Galaxy feature. When its config parser sees
an environment variable GALAXY_CONFIG_XXX, it will use its value to override the `galaxy.yaml` 
parameter `xxx`.

## Starting the container(s)

### Galaxy container

- In a terminal, create a directory that will be bind-mounted to keep Galaxy data alive across container restarts: `mkdir galaxy_storage`
- `docker create -v /export --name galaxy-store bgruening/galaxy-stable /bin/true`
   This is a big image - will take a while to pull.
- `docker run -d -p 8080:80 --privileged --volumes-from galaxy-store bgruening/galaxy-stable`
  We use `--privileged` to auto-mount reference data through CVMFS (works on Windows?)
- Access container in Chrome at `localhost:8080`.
- Go to User->Preferences->Manage API key. Click Create a new key. 
  Copy the key somewhere to use in your client R session.

### R Studio Container

*You can also use some other R, but we installed a couple of necessary packages into our container*

- `docker run -v /home/rstudio/work2 --name rstudio-work sliders/rstudio-bcbiornaseq:v2 bash -c 'chown -R rstudio. /home/rstudio/work2'`
  We created a volume owned by the user `rstudio` from the container
- `docker run -d -p 8787:8787 -e PASSWORD=bcbio -e ROOT=TRUE --volumes-from rstudio-work  sliders/rstudio-bcbiornaseq:v2`
- Access the R Studio Server at `localhost:8787`
- Login with user `rstudio` and password `bcbio`
- Open Tools->Terminal, and `cd work2 && git clone <this repository>`
- `sudo apt-get install python-pip`
- `sudo pip install -U git+https://github.com/andreyto/parsec.git@at_fixes`
  Installs my branch of that package with some bug fixes

## Working in R

The API and bindings from different languages are described [here](https://galaxyproject.org/develop/api/)

### Define API key and URL
```{r}
GAL_URL="http://<YOUR_HOST_IP>:8080"
GAL_API_KEY="73c730a5ac10f80d363bcd46b4ca28a8"
```

At first, we will still run command from the terminal:

Run init and type your URL and key
```
parsec init
```
Downlaod dataset
```
parsec datasets download_dataset f2db41e1fa331b3e
```
